### ISSUE TITLE
Changes suggested

### ISSUE THREAD

**Issue by mauriciomonta** [jpol01/Portfolio#8]
Line 128 to 133 (index.html)
`<p class="u-card-p">
            A daily selection of privately <br />
            personalized reads; no accounts or <br />
            sign-ups required. has been the <br />
            industry's standard
          </p>`

You should adapt the text using CSS instead use `<br>` for each line.

**Comment by Kakalanp** [comment]
`.card-row2` to `.card-row8` are styled equaly, please consider using only one of those as you are repeating lines of code otherwise.
